### PR TITLE
Added compact-toolbars

### PR DESCRIPTION
**Pull request by AlexVallat**
The "Compact" setting for toolbars is still way less compact than it used to be on 56 with CTR. This tiny css fixes that.

### CODE REVIEW

**Comment by Timvde** [comment]
I would like to add an extra comment that this tweak assumes that you already enabled compact density in Firefox itself. I'm not sure if this is what you intended, but with normal density, the back button looks weird. With touch density, all icons are off for me. Diff below. If I get green light from you, I'll merge. Also included are some minor whitespace fixes.

```
--- a/toolbars/compact-toolbars.css
+++ b/toolbars/compact-toolbars.css
@@ -1,9 +1,11 @@
-/* 
+/*
  * Make the toolbar extra-compact (similar to v56 with CTR)
  *
+ * This assumes that you have set the built-in density to compact
+ *
  * Contributor(s): Alex Vallat
  */
- 
+
 #urlbar,
 .searchbar-textbox {
   font-size: unset !important;
@@ -16,4 +18,4 @@
 
 #main-window #nav-bar .toolbarbutton-1 {
   padding: 0px !important;
-}
\ No newline at end of file
+}
```

**Comment by AlexVallat** [comment]
Yes, this is just for the compact density. I've added changes to make that explicit, and prevent it applying if the density is not set to compact.

**Comment by Timvde** [comment]
Oh, I didn't know that that was possible, cool! Thank you!

**Comment by Timvde** [comment]
I squashed your commits and pushed manually, seems like GitHub doesn't recognize that :) Thanks again!

**Pull request closed without merging**
