### PR TITLE
Reload button inside addressbar, on the left

### PR DESCRIPTION
**Pull request by Madis0**
A shameless fork of pull request #47, because this _cannot_ sensibly be done with an extension (only if I moved the whole pageaction group to the left), at least not yet.

### CODE REVIEW

**Comment by Timvde** [comment]
I see this when I mouseover the icon: https://i.imgur.com/OjRw4Hh.png

I need to set `margin-left` of the container to -2.2em to correct this. To then fix the mouseover shadow of the identity box, I also have to decrease its value to -1.7em. What do you think of this change? It makes the urlbar a little wider, but I actually like the extra spacing. It's also on the right side (if you didn't change that).

**Comment by Madis0** [comment]
I guess that is the 57/58 difference again, I should really test my styles on stable too 😂
So you can fix it for the 57 branch, but keep it on 58+.

> It's also on the right side (if you didn't change that).

What do you mean by that?

**Comment by Timvde** [comment]
> I guess that is the 57/58 difference again

It still looks the same to me on 59 on Linux.

> What do you mean by that?
The right side of the location bar has some padding, so for consistency, the left side should have this padding too.

**Comment by Madis0** [comment]
Seems more like OS/desktop env difference again. Between FX versions there is a minor padding change, but not that drastic to look ugly

Here's how it looks for me with default toolbar and moved reload button:

**Comment by Timvde** [comment]
Looks a lot better indeed. Could you add a small comment at the relevant line that it is optimized for Windows, and maybe add my settings commented out for Linux (I would not go as far as to add `-Windows` to the file name, since it's only a minor visual glitch).

Also, just noticed this now, but I don't think referencing to the old PR is necessary or even useful. Do keep Admicos' name in there, though :)

**Comment by Madis0** [comment]
Well, I never tested it with Windows though. That's GNOME with [Adapta](https://github.com/adapta-project/adapta-gtk-theme) 😉

**Comment by Timvde** [comment]
Oh, I missed that. Should've gotten it from the font in your title bar. Damn it :P

Just add a small comment that the values might need to change depending on the platform and it's good to go.

**Comment by Timvde** [comment]
Good enough for me :)

**Comment by Timvde** [comment]
Hi :)

I'm not sure how to contact you, so let's just reply here. I'm sorry if I wasn't clear on this, but could you please not push directly to master, but keep on using pull requests that I can review first? As you said yourself: my input has helped you before, and I maybe could've caught the typo you made. By giving you push access, I was more thinking about giving you the right to review and merge other people's pull requests, instead of directly pushing to master.

**Comment by Madis0** [comment]
@Timvde Right, sorry about that.

**Pull request merged**
