### PR TITLE
Merge tabbar and navbar (Linux)

### PR DESCRIPTION
**Pull request by Madis0**
I reviewed the code and modified it a bit, it looks quite good on my end but YMMV.

Compact: https://www.pictshare.net/pbu075lbk5.png
Normal: https://www.pictshare.net/p4snhmwtm3.png

### CODE REVIEW

**Comment by Timvde** [comment]
You can use `:root[uidensity=compact]` to make a style only apply on compact density. I suppose similar selectors also exist for other densities. Could you apply them please? In that case, would it be possible to merge both files?

**Comment by Madis0** [comment]
The transition looks very immersive with the selectors, as if it was built-in. Thanks for the suggestion!

**Comment by Timvde** [comment]
I just tested this, and it looks quite bad for me... (Linux/KDE). This appears to be because I'm testing in a clean profile, which still has the home button and flexible space. Tabs overlap the location bar (even still if I make the location bar as small as possible). I think you should move the tabs just a little to the right, so it looks sort of decent on the default Firefox layout. Apart from that, since this file is *very* sensitive to small changes in the layout of users. Maybe it would be a good idea to put some of the important variables (like left-padding) into variables with a descriptive name, so that it's easier for users to configure?

**Comment by Madis0** [comment]
I guess I forgot to mention it is made for back-forward-reload without spacers and home, though the overflow menu works too.

I'm not sure what to put into variables, because as you said, it is very sensitive to changes and when ones must be made, they are probably in not just one variable. For the specific changes, I added inline comments to help.

**Comment by Timvde** [comment]
Well, further down the road, I want to look into making a configuration system based on CSS variables, so it would be easier for me to expose them :)

**Comment by Madis0** [comment]
I have now made most values a variable, with comments on variable definition rows.

**Comment by Timvde** [comment]
Oh, I think I didn't make myself really clear, sorry. I didn't mean for you to put *everything* in a variable, just the ones that define left/right positioning, which is the brittle part of his style. This would make it easy for anyone not really knowing CSS to know which values to change. Also, I meant to call them call them `--tabs-padding-left`, but `--space-before-tabs` or something.

Sorry again for the confusion! I'm giving it a try now, and will post this for you to review, if that's okay for you :)

**Comment by Timvde** [comment]
So, here's what I came up with. What do you think of this approach? I made a section specifically for values I think should be customized based on the browser, and another for values that I think are static based on density. I also moved static values back into the style itself, instead of making them configurable.

I tried to figure out what `--tabs-margin-left` is supposed to make space for, to give it a descriptive name, but I couldn't figure it out. It appears that I can set its value to zero without breaking anything. But I might be doing something wrong :)

```css
/*
 * Place the navigation bar in the front of the tab bar (Linux)
 *
 * Contributor(s): Madis0
 */

/* Variable values depending on layout. Use these to customize style. */

/* Compact density */
:root[uidensity=compact] {
  --tabs-margin-left: 5.5em; /* Keep margin for button background */
  --space-before-tabs: 34.5em; /* Left margin for nav bar */
  --space-after-tabs: 2em; /* Right margin for caption button, menu */
}

/* Touch density */
:root[uidensity=touch] {
  --tabs-margin-left: 7.5em; /* Keep margin for button background */
  --space-before-tabs: 34em; /* Left margin for nav bar */
  --space-after-tabs: 2.3em; /* Right margin for caption button, menu */
}

/* Normal density */
:root {
  --tabs-margin-left: 6.4em; /* Keep margin for button background */
  --space-before-tabs: 34em; /* Left margin for nav bar */
  --space-after-tabs: 2em; /* Right margin for caption button, menu */
}

/* Static values only depending on touch density */
:root[uidensity=compact] {
  --nav-margin-top: -1em;
  --menu-margin-top: 0.05em;
}

:root[uidensity=touch] {
  --nav-margin-top: -2.5em;
  --menu-margin-top: 0.1em;
}

:root {
  --nav-margin-top: -2.3em;
  --menu-margin-top: 0.15em;
}

/* Adjust tab bar to get space first */
#TabsToolbar {
  margin-left: var(--tabs-margin-left) !important;
  padding-left: var(--space-before-tabs) !important;
  margin-right: var(--space-after-tabs) !important;
  margin-bottom: -0.1em; !important; /* Remove bottom border */
}

/* Move nav bar to top left */
#nav-bar {
  margin-top: var(--nav-margin-top) !important; /* Move nav bar up */
  margin-right: 60vw !important; /* Cut it off with defined width */
  margin-bottom: -0.3em !important; /* Remove bottom border */
  background-color: transparent !important; /* Make it use tab bar colors */
}

/* Move menu button to top right */
#PanelUI-button {
  position: fixed; /* Fixed position for menu */
  top: var(--menu-margin-top); /* Add some margin to top */
  right: 0em; /* Move it to right side (adjust for caption buttons) */
  border-left: none !important; /* Remove menu border */
}
```

I must say, it's still not looking good for me. I have some extra pixels above the location bar, and some empty space below the tabs. Maybe it has something to do with KDE? Here's a screenshot: https://i.imgur.com/OCbqeQc.png. This also happens with your latest style, so I don't think I messed up my values here.

**Comment by Madis0** [comment]
> I tried to figure out what --tabs-margin-left is supposed to make space for, to give it a descriptive name, but I couldn't figure it out. 

It is the white background that appears on normal theme only, in order to make back-forward-reload and menu visible, note the screenshots on OP.

> I must say, it's still not looking good for me. I have some extra pixels above the location bar, and some empty space below the tabs. Maybe it has something to do with KDE?

Try adjusting `--nav-margin-top` and tabs'/nav's `margin-bottom`. It must be a KDE thing, as I've now tested different GTK+ themes (sic) on GNOME and they don't affect it at all.

**Comment by Madis0** [comment]
Looking at your review code now, you must've broken something with your edits as it looks wrong to me too.

**Comment by Madis0** [comment]
Looking at the review code, you broke this on compact:
`--nav-margin-top: -1em;`
Should be `--nav-margin-top: -2em;`

**Comment by Timvde** [comment]
> It is the white background that appears on normal theme only, in order to make back-forward-reload and menu visible, note the screenshots on OP.

Right. I had just deleted the value for `--tabs-margin-left`, which made it fallback to the normal density value. That's why I didn't see it.

> Looking at the review code, you broke this on compact

Ah, nice catch! Sorry for my stupidity :) It still looks off, though. I was really hoping that this would work somewhat consistent, without the need to tweak *too* much for users. Maybe I should go with your "variables all the way" version anyway and add a big warning at the top.

**Comment by Madis0** [comment]
Fixed the values for Firefox 58, maybe needs to be in a separate branch?

**Comment by Timvde** [comment]
All right, I have a few hours time to go through all pull requests. I'm going to merge all Fx 57-compatible PRs and branch off the release branch. If you want this style to be available in Fx 57, you should revert the last commit and afterwards submit it as a separate PR. Does this style still assume only back/forward/reload without home button and spacers? In that case, you should probably add it as a comment :)

**Comment by Madis0** [comment]
> If you want this style to be available in Fx 57, you should revert the last commit and afterwards submit it as a separate PR. 

Eh, let it be.

>Does this style still assume only back/forward/reload without home button and spacers? In that case, you should probably add it as a comment :)

Just tested and it works with default layout too.

**Comment by Timvde** [comment]
Awesome! I'm just going to believe you, since you've done tons of good work in this repo already :) If you want, I can give you write access and you can become co-maintainer? I started this repository out of necessity, but as you may have noticed, I am probably not the best maintainer. It also doesn't help that I barely know any CSS at all.

**Comment by Madis0** [comment]
Sure, I could push my contributions directly, but you're usually the one to point mistakes/modularity out in them. 😀

**Comment by Timvde** [comment]
If you want, I can still review your changes :) I should have more time when the holidays are over, so I don't expect that to be a big problem. But you could help review and merge other contributions. If you're interested, could you join Mozilla IRC and pm me so we can have a talk? (Timvde)

**Pull request merged**
