### PR TITLE
Create vertical-context-navigation-Linux.css

### PR DESCRIPTION
**Pull request by MrOtherGuy**

### CODE REVIEW

**Comment by MrOtherGuy** [comment]
The method for getting Linux layout to work is different than in the merged Linux+Win file but seems to work fine on my testing. I removed the margin/padding hack and used different values for vertically positioning other items.

**Comment by Timvde** [comment]
Seems to work, thanks! Since I'm a bit of a git purist, I'm just going to take this file and add it together with the other file in one commit if you don't mind :)

**Comment by MrOtherGuy** [comment]
Nice to hear it works. But go ahead, I would have preferred them in one place but just couldn't find another way to create a new file.

**Comment by Timvde** [comment]
Just create the file and run `git add file` :) Anyway, merged :) Thanks!

**Pull request closed without merging**
