### PR TITLE
Fix move-identity-lock-right.css for Photon

### PR DESCRIPTION
**Pull request by Madis0**
Fixed the style to look right on latest Nightly, also added inline comments to code.
You can keep the original in a separate branch (FX 56) I guess, but I won't help maintain it as I only want my Photon-supported styles here.

### CODE REVIEW

**Comment by Madis0** [comment]
Seems like the autocomplete broke again 😭 Also, in FX 57 it would make sense to move it before dropdown and three dots, to make approaching buttons easier (if I only knew how...).

**Comment by Timvde** [comment]
I'm also more inclined to mostly focus on supporting Photon. For most tweaks, an add-on already exists in Fx 56 and earlier.

With your comment ,do you mean that the style is currently broken? Both the original one and the fixed on in this PR?

**Comment by Madis0** [comment]
Unfortunately yes, it seems like it is broken at the moment (to be more precise, only the autocomplete part - it needs some pixel re-tuning, haven't figured out the correct values yet). Do I have to delete or close this?

**Comment by Timvde** [comment]
If you're planning to fix this somewhere in the near future, you can leave it open. If you're not going to work on this for a long time, it would probably be clearer if it's closed. You can then of course open a new PR at any time.

**Comment by Madis0** [comment]
I figured I should post the fix for moving the identity box to the left of dropdown/3-dot menu before forgetting about it. Haven't managed to fix the autocomplete yet though, [hoping reddit users will help out](https://www.reddit.com/r/FirefoxCSS/comments/73dr1j/debugging_autocomplete_entries/).

**Comment by Madis0** [comment]
Improved the style once again, but still haven't managed to fix the autocomplete.
(In my defense, it is readable although misaligned with my tabbar-navbar merge patch #26)

**Comment by Timvde** [comment]
Wow, the misalignment issue is bad and definitely needs to be fixed. However, the issue already exists in the old style, and this is definitely an improvement for the page action button, so I'll merge it.

**Pull request merged**
