### PR TITLE
Adding a tweak to style private windows' toolbars with dark theme colors

### PR DESCRIPTION
**Pull request by dtwist**

### CODE REVIEW

**Comment by Timvde** [comment]
This doesn't do anything for me. Is it OS-dependent?

**Comment by Madis0** [comment]
Tip: there seems to be [an extension for this now.](https://addons.mozilla.org/en-US/firefox/addon/private-browsing-theme/?src=search)

**Comment by spikespaz** [comment]
I have also made this:
https://github.com/spikespaz/firefox-nativedark/
https://addons.mozilla.org/en-US/firefox/addon/native-dark/

**Comment by Timvde** [comment]
I'm going to close this, since an extension is definitely the better solution. Thank you for your contribution anyway!

**Pull request closed without merging**
