### PR TITLE
hide-zoom-indicator

### PR DESCRIPTION
**Pull request by BubiBalboa**

### CODE REVIEW

**Comment by Timvde** [comment]
Thank you for your contribution!

A line still appears that's normally in between the zoom indicator and the page button. Maybe that should be removed too?

**Comment by Timvde** [comment]
Hmm, the vertical line still appears for me. It looks like this: https://i.imgur.com/zohsdzt.png and only appears after zooming in or out. Tested in today's Nightly.

**Comment by BubiBalboa** [comment]
I'll investigate but I have no idea what I'm doing to be honest. If you know what's wrong with the style I wouldn't be offended if you would tell me.

**Comment by Timvde** [comment]
I sadly have no idea either. I'm just maintaining this repository because no-one else stood up to do it. I might have some time this weekend to look into it, though. But I can't promise anything. If I can't find it, I'll just take the code as-is and create an issue.

**Comment by BubiBalboa** [comment]
Might be a Nightly thing. I'm on the latest stable and now also tried the style on a fresh FFportable 55.0.3 and it works for me.

**Comment by Timvde** [comment]
Oh yea, that *definitely* is a Nightly thing, I wasn't doubting that for a single second. The goal of this repository is mainly being a pool of customizations for 57 and later, when legacy add-ons cease to exist. So while it is great when styles work for 55 or 56, I mainly aim for them to work in 57.

**Comment by BubiBalboa** [comment]
Okay,  installed Nightly and I think i figured it out. Should work now.

**Comment by Timvde** [comment]
Awesome, works great! Thanks!

**Pull request merged**
