### PR TITLE
Configure background color of new tabs while loading (white flash)

### PR DESCRIPTION
**Pull request by galacticdessert**
This css is to remove/change the default background color of an empty new tab, the current selection is black.
It can also be used to remove the annoying white flash that happens when a new tab is opened and a replacement for the new tab is used, like Tabliss

### CODE REVIEW

**Comment by Timvde** [comment]
Is this different from https://github.com/Timvde/UserChrome-Tweaks/blob/master/activitystream/activitystream-dark-userContent.css ?

**Comment by galacticdessert** [comment]
I think so, this is to remove the annoying white flash when opening a new tab.

[Before](https://streamable.com/j3hgv)
[After](https://streamable.com/j82b6)

**Comment by Timvde** [comment]
Oh, I guess I had to link to the `userChrome.css` change instead of the `userContent.css`, more specifically this commit: https://github.com/Timvde/UserChrome-Tweaks/commit/0b8037a67dd6753665d6eac1159c60d76fb0d91e

You're styling different elements though, so I'm not sure. Could you move it to the `activitystream` directory in any case? Since this is not directly about the tabs themselves, but more to the new tab page.

**Comment by galacticdessert** [comment]
I realized that my css change also affects the title bar, and it was not the desired effect.
I will close this PR and make a new one if I find a fix for it.

**Pull request closed without merging**
