### PR TITLE
Added css rule to reduce the height of tabs when in compact mode

### PR DESCRIPTION
**Pull request by DrPugsley**
Okay, did a `git reset --hard` and a few other things to clean up my commits and make my fork not just be a giant mess. Thanks for your help!

### CODE REVIEW

**Comment by Timvde** [comment]
Ah, did I forget to mention last time? No need for the namespace line, and I think the `@-moz-document` line is unnecessary too. This repository is meant as a collection of styles, not taking into account the management overhead. I am also planning to create a Python script that will `@import` these styles in `userChrome.css` and will take care of all this stuff.

**Comment by DrPugsley** [comment]
Alrighty, fixed it! Also that python script sounds amazing, can't wait for that!

**Comment by Timvde** [comment]
In testing this, I noticed a *very* small issue: the tab border doesn't nicely align with the rest of the browser interface in customize mode. This appears *only* in customize mode though, afaict, so I don't consider this a blocking issue. I added your style to the repository, if you ever find a fix, you're welcome to add it.

I'm not sure about the timeline of the Python script by the way. I have my hands full at the moment with managing this repository next to my day job and hobbies. I am also focusing it on Linux only at the moment, since I don't have any other platforms. But if it takes off, I expect people to submit pull requests to make it platform independent :)

Anyway, thanks again for your contribution!

**Comment by DrPugsley** [comment]
Linux only works for me :)

Also I'll look into that issue and see if there's anything I can do about it

**Pull request closed without merging**
