### PR TITLE
Create dark-thin-context-menu.css

### PR DESCRIPTION
**Pull request by jy1263**

### CODE REVIEW

**Comment by Timvde** [comment]
Could you add the template header with a description (and preferably also a screenshot)? cfr. https://github.com/Timvde/UserChrome-Tweaks/blob/master/template.css

**Comment by jy1263** [comment]
sorry about commiting twice

**Comment by jy1263** [comment]
alright, added the header, should be okay now.

**Comment by Timvde** [comment]
Thanks!

**Pull request merged**
