### PR TITLE
Move the hamburger menu to the top left

### PR DESCRIPTION
**Pull request by AlexVallat**
This moves the hamburger menu to the top left, to the left of the first tab, in the handy blank space that's available there if the window isn't maximised. If it is maximised, then that blank space is inserted anyway so there's room for the menu button. This is more or less where the original Firefox menu button went, as opposed to the Chrome standard of having it as a toolbar button at the right.

Only tested on Windows 7 - if others want to test (and tweak if necessary) for other OS'es, that would be cool.

### CODE REVIEW

**Comment by AlexVallat** [comment]
I'm not sure why git is listing all the earlier commits, only the last one is relevant to this pull request.

**Comment by Timvde** [comment]
Try something like:

`git fetch --all`
`git rebase -i HEAD~ --onto Timvde/master` (or whatever my master branch is called for you)

**Comment by AlexVallat** [comment]
Ugh, I really dislike git. OK, I'll try rebase instead of merge next time I need to sync changes from your master. There are dire warnings about doing rebase if you've already pushed changes or made a pull request, so I won't attempt to do anything to this one.

**Comment by Timvde** [comment]
You just don't know git well enough yet ;) The "problem" is that I really like rebasing (it gives me a super-clean history) and that I always do that instead of merging the PRs. I guess I might want to re-evaluate that on a public repository... This is not the first time it's giving head-aches to other people who don't know git as well, and my repository is only a week old or so :/

Anyway, you can safely do the commands I told you and then `git push --force`. The owner of the receiving repository approves ;) (Otherwise, I'll just have to do it myself)

**Comment by AlexVallat** [comment]
Well that's just made things worse as far as I can see... maybe it looks better to you in some way though?

**Comment by Timvde** [comment]
Ehm, I'm not sure where the merge comes from... Did you use the Github interface instead of the command-line? It's okay, I'll just fix it, that's probably easier ;) Sorry for the hassle. I've been looking into this, and the solution is probably that contributors should not use their master branch to develop anything, but *only* to track my master branch. I'm going to add that to the contributing guidelines.

**Comment by AlexVallat** [comment]
I used the command line to enter the magic incantations you specified, then the UI to pull and push back to the server. Sorry if I've spoiled your clean history!

**Comment by Timvde** [comment]
It's okay, I'm looking at the local tree now, and it's not that bad. The rebase worked as expected, but you later merged your old commits into the branch again, and that's what makes it messy. Let's try this one more time :)

`git reset --hard "HEAD^"` (quotes not needed in all shells, but it's safer to put them)
`git push --force`

If you want an explanation of what I did and become a git guru yourself, you can find me on Mozilla IRC as Timvde ;)

**Comment by AlexVallat** [comment]
That looks better now, thanks.

**Comment by Timvde** [comment]
I added a small section about git usage to the contributing guidelines. Your PR looks fine, and it seems to work great in Linux too. Since you're putting the button on the *left* of the tabs, I'm going to look for a macOS machine to test on though, since it has window buttons there.

**Comment by Timvde** [comment]
I was afraid so. In windowed mode, the hamburger menu is now positioned behind the window controls: https://i.imgur.com/OLIgWwP.png

Do you think you can fix this? If not, rename the file to give it a `-Linux-Windows` suffix please :) You can `git commit --amend` to add it the current commit. Afterwards, you'll need a `git push --force`

**Comment by AlexVallat** [comment]
I don't have access to a Mac, so I won't be able to tweak it to work for that. Perhaps someone else can, or if they have the buttons on that side perhaps it wouldn't make any sense to put the menu button there too.

**Comment by Timvde** [comment]
That's completely fine for me! Unrelated: hmm, I was hoping that Travis would just shut its mouth until it was configured, but apparently not. I first have some more finding out how it works to do, so just ignore the failing build.

I'd rather have you squash your commits together if you don't mind. I really like my git history as clean as possible, and having it in the repo at some point without the suffix, while it is not applicable to macOS, is suboptimal imo.

Quick guide, in case you're not a git guru:

- `git fetch --all` (just in case)
- `git rebase -i Timvde/master` (or however my branch is named for you)
- Change the `pick` before the second commit to `fixup`
- Save and close your editor

Thanks! I'll make sure to have Travis disabled by then, so merging isn't blocked :P

**Comment by AlexVallat** [comment]
Interactive rebasing isn't working, complaining of missing files. I am far from a git guru, and getting further by the minute. I begin to doubt that it is fit for purpose at all. Can I suggest you simply copy and paste the css into a file of your choosing, that would probably be easier?

**Comment by Timvde** [comment]
Nah, it's okay, I'll just do the rebase. Strange that it isn't working for you. Git is really nice for this purpose, I'm probably just too demanding... Sorry :/ You're not the only one for whom this turned out to be a problem, so I'll think of changing my policy if this continues to be a problem.

**Comment by Timvde** [comment]
Manually merged.

**Comment by Timvde** [comment]
Hi Alex! This is probably the easiest way to contact you. I just wanted to tell that based on feedback from you and some other people, I have come up with a solution that should fit everyone. I found out that Github has the option to squash and rebase all commits when merging, which is exactly what I always want to do. The only thing I need to request from contributors to achieve the clean history that I'm after, is that they only add one style per pull request. Apart from that, the history can be arbitrarily messy, and a click on the button fixes it for me. Does that sound reasonable to you?

It's the first time I maintain a public repository, so I'm also still searching for the best way to do this. Sorry for all the hassle, and thanks again for your feedback and contributions! I really appreciate it :)

**Comment by AlexVallat** [comment]
Hi, I think one style per pull request is a reasonable requirement. The only caveat I would have about that is what counts as "one style"? One file is presumably one style, but what about multiple files with different OS suffixes? Or multiple files for options (autohide-navbar-left.css, autohide-navbar-centre.css, autohide-navbar-right.css, for example)?

If I've understood right, the contributors fork will still contain their full history of revisions as they work on the style, but your master repository contains only a single commit when you accept the final agreed pull request from them? Sounds ideal.

**Comment by Timvde** [comment]
> If I've understood right, the contributors fork will still contain their full history of revisions as they work on the style, but your master repository contains only a single commit when you accept the final agreed pull request from them? Sounds ideal.

Correct.

> what counts as "one style"?

One particular change to the browser UI. OS suffixes can definitely be submitted together (and I would prefer it). With regard to different options, I'm more in the middle. I'd be happy with both.

**Pull request closed without merging**
