### PR TITLE
made the activity stream look decent with dark theme

### PR DESCRIPTION
**Pull request by andreicristianpetcu**
https://imgur.com/a/WcxGk

### CODE REVIEW

**Comment by Timvde** [comment]
Hmm, I actually didn't think about `userContent.css` tweaks yet.

What does the `userChrome.css` style exactly? I have a hard time seeing a difference.

**Comment by andreicristianpetcu** [comment]
userChrome is for Firefox UI while userContent is for the web pages. Things get a little blured since activity stream is made out of web pages inside Firefox.

**Comment by Timvde** [comment]
I know what it does :) I just didn't think about it when creating this repository, and I was hoping not to create any dependencies between files (that would make it *a lot* harder to automate managing the files).

And ah, it's for the initial flicker, that explains a lot :) I don't think there's a better way to do this. I'm going to just accept this PR as as, and worry later about managing `userContent.css` tweaks and dependencies between multiple styles.

**Comment by Timvde** [comment]
Oh, one more thing: could you follow the style guidelines for indentation? Just two spaces please :) I'd like to keep code style in this repository more or less consistent. Thanks!

**Comment by andreicristianpetcu** [comment]
I'll try to do this in a few hours.

**Comment by andreicristianpetcu** [comment]
it should be fine now

**Comment by Timvde** [comment]
And you even amended your change, nice! Thank you!

**Comment by andreicristianpetcu** [comment]
I know it is considered basic politeness on GitHub to squash commits. I personally hate it but as a maintainer I can see the benefit :)

**Pull request merged**
