### PR TITLE
Highlight broken padlock

### PR DESCRIPTION
**Pull request by Madis0**
By adding a red background

### CODE REVIEW

**Comment by Timvde** [comment]
Looks like for most links on https://badssl.com/ don't trigger this. Many just don't have a lock at all :( Is it possible to detect https and the absence of a lock with CSS? I think not, right? If so, I'll just merge at is. Otherwise, this could be a nice improvement.

**Comment by Madis0** [comment]
>Is it possible to detect https and the absence of a lock with CSS?

Before the config setting for enabling broken lock on all http was added, I used to do it by reskinning info icon to the broken lock and hiding it on https sites. 😀

There should be some more states for broken locks indeed though, I'll take a look when I get the time.

**Comment by Madis0** [comment]
>Looks like for most links on https://badssl.com/ don't trigger this.

I see what you mean now. Though I believe it is rather a Firefox issue worth reporting, than me trying to work around it with CSS.

Regardless, added selectors for all broken locks as defined by browser.css.

**Comment by Timvde** [comment]
I was confused for a minute about the extra commit and I was about to ask you to create a separate PR for it, but it's just a reference. You read my mind! Thanks!

I agree that this is a bug in Firefox. I'll check in #security on IRC and see what they think.

**Pull request merged**
