### PR TITLE
Added Hide Tabs (like MacOS) for Windows

### PR DESCRIPTION
**Pull request by Ivan0xFF**
Added Hide Tabs with merged title bar and navigation bar tweak for Windows.

This is different than hide-tabs-linux-windows-titlebar.css in that it merges the title bar and navigation bar. It's the same as hide-tabs-macos.css but works on Windows.

Tested with Windows 10, FF 57 and 58.

capture

### CODE REVIEW

**Comment by Timvde** [comment]
Awesome, I was already hoping someone would do this :) Thank you for your contribution, and sorry for taking so long to get back to you! I'll try to test this later today (I don't have a Windows machine at hand).

**Comment by Timvde** [comment]
This is really cool! Could you please also rename `hide-tabs-linux-windows-titlebar.css` to `hide-tabs-linux-titlebar.css`? And your file is missing a newline at the end. It should be there [according to POSIX guidelines](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline). Could you please add that too? Thanks!

**Comment by Ivan0xFF** [comment]
Alright, I've updated my branch with your requested changes.

**Comment by Timvde** [comment]
Thanks a lot!

**Pull request merged**
