### PR TITLE
Sliding bookmarks

### PR DESCRIPTION
**Pull request by Admicos**
I did **not** make this, however the original source is linked on the file so i hope it's ok.

Also, i wasn't entirely sure where to put this so i put it under `toolbars/`. If that's the wrong directory just tell me.

### CODE REVIEW

**Comment by Timvde** [comment]
I would love to add this, since it's a very nice style, but there is no license set on userstyles.org, which basically makes it proprietary... There is no way for me to legally redistribute this code. I fear that I can only add it if the original author gives permission to relicense it as GPL.

`toolbars/` is the appropriate directory, imo.

**Comment by Admicos** [comment]
It was last updated ~2 years ago so I feel like it would be hard to get permission. I'd try to re-make it but the CSS would probably be similar so I'm not sure if that would work or not.

**Comment by Timvde** [comment]
It is the right thing to do, so I would like to try that first. I don't have a userstyles.org account, so I can't send him a message. Do you, and if so, would you mind trying?

**Comment by Admicos** [comment]
I just sent him a message asking for a license, will update when he responds.

**Comment by Admicos** [comment]
I got this reply.

> By default I had specified it as CC BY-NC-SA - Creative Commons Attribution-NonCommercial-ShareAlike. If you're going to make modifications and distribute, it'd be nice if you leave some sort of attribution for my original code. :)

So, it should be fine as long as the original link and license stays.

**Comment by Timvde** [comment]
It's code, it shouldn't be CC... *sigh* :P But let's do that then, thanks! Would you mind adding the license to the file (including a link to https://creativecommons.org/licenses/by-nc-sa/4.0/) and provide his name explicitly like in other files (`Contributor(s): name`)? You can then squash your commits to a single one and rebase if necessary. Then I'll merge :) Thanks!

**Comment by Admicos** [comment]
I think it's CC since [userstyles.org only shows CC licenses on their panel.](http://i.imgur.com/ybY8LhO.png).

I'm not entirely sure if I squashed correctly (I never tried squashing even through I used git for a year or two) but it should be ok now.

**Comment by Timvde** [comment]
You added it to my latest commit, so no, that was not how you were meant to do it :)

You should be able to just do `git rebase origin/master` (or however my master branch is called in your repository) to fix it.

**Comment by Admicos** [comment]
I just reset and re-pushed the file. It should be a single commit now.

**Comment by Timvde** [comment]
You didn't rebase on master, though, so I had to rebase and lose your "Verified" tag :( But it's not *that* important, luckily :P Thank you for your work!

**Pull request closed without merging**
