### PR TITLE
Create 1px-padding-over-tabs.css

### PR DESCRIPTION
**Pull request by BubiBalboa**

### CODE REVIEW

**Comment by Timvde** [comment]
Did you check that the original author is fine with submitting the style and making it GPL?

**Comment by BubiBalboa** [comment]
Yes, he is aware and approves.

**Comment by Timvde** [comment]
In that case: thank you both!

**Comment by Timvde** [comment]
Looks like [this will be a setting in Firefox 57](https://bugzilla.mozilla.org/show_bug.cgi?id=1349552) ([here's the gif](https://dolske.files.wordpress.com/2017/09/dragspace1.gif)). Is there any reason to keep it, or do you think we should back this out?

**Comment by BubiBalboa** [comment]
Good question. Nice to see they will add that setting. In the gif it looks way to big for my taste though. I'd say delete that style and I'll add it again if the official setting needs tweaking.

**Comment by Timvde** [comment]
Yea, even before your edit, I wanted to reply "Let's keep it instead, and see if we get rid of it later". I'll leave it in for now. Thanks for your feedback! :)

**Pull request merged**
