### PR TITLE
Added auto-hide nav bar

### PR DESCRIPTION
**Pull request by AlexVallat**
This auto-hides the nav bar. It will auto-show on mouse hover, or if it gets the focus.

### CODE REVIEW

**Comment by Timvde** [comment]
Cool! There still seems to be some unused space left for me on Linux, but I don't consider it a blocking issue. Unless you really want to look into it, I'm merging :)

**Comment by AlexVallat** [comment]
Strange, on Linux there's an extra 4px vertical padding, for some reason. I've added explicit zeroing of this which should resolve the issue. No idea what happens on the Mac, I'm afraid.

**Comment by Timvde** [comment]
Cool! I suppose the change to compact-toolbars doesn't affect the style when the auto-hide nav bar style is not enabled?

**Comment by andreicristianpetcu** [comment]
I see you have no screenshot/screencast of this change. You can use [this video](https://vimeo.com/234896585) if you wish.

**Comment by Timvde** [comment]
In the video (and in my own test now), there is a white border at the bottom of the trigger area. Can this be solved?

In compact mode, it also messes with the bottom of the location bar, I guess the height of the toolbar might need one or two extra pixels?

**Comment by AlexVallat** [comment]
Ah, yeah, looks like it's not quite right on Linux. I'll set up a VM and do some tweaking. Thank you for the video, @andreicristianpetcu , but it seems this isn't quite ready on Linux yet! Should be flawless on Windows 7, though.

**Comment by AlexVallat** [comment]
Hmm. It's working just fine on Linux Mint Mate and Windows 10 (the two VMs I had handy for testing), could you tell me what Linux distro you are using that exhibits the problem?

**Comment by franglais125** [comment]
@AlexVallat I can confirm this line appearing on Debian 9 (stable).

**Comment by Timvde** [comment]
I'm using Arch Linux with KDE. If I'm not mistaken, @andreicristianpetcu is a Fedora user (and by the looks of the file manager, he's using GNOME).

**Comment by AlexVallat** [comment]
Thanks, I've made a tiny tweak that should resolve the issue on those window managers. I don't know why it should be different between window managers, but this should be fine now.

**Comment by Timvde** [comment]
This is pretty great, thanks a lot!

**Comment by Aiolikos** [comment]
It works man!thank you... but is it possible to hide the bookmarks bar too and appear only on focus mode like on beyond Australis? It will be really awesome! Thanks in advance.

**Comment by AlexVallat** [comment]
I've created a new pull request which includes the bookmark bar in the auto-hiding: https://github.com/Timvde/UserChrome-Tweaks/pull/67

**Pull request merged**
