### PR TITLE
Autohide "Reload in address bar"

### PR DESCRIPTION
**Pull request by Madis0**
Automatically hides [the icon of this extension](https://addons.mozilla.org/en-US/firefox/addon/reload-in-address-bar/), showing up only on address bar hover.

### CODE REVIEW

**Comment by Timvde** [comment]
There's at least one more add-on like this: https://addons.mozilla.org/en-US/firefox/addon/australis-refresh-in-url-bar/

It might be a good idea to add support for that add-on too.

**Comment by Madis0** [comment]
Good point, added support to the three extensions I could find. I think the code could be compacted with [moz-any](https://developer.mozilla.org/en-US/docs/Web/CSS/%3Aany), but I couldn't figure out the proper syntax at this point.

**Comment by Timvde** [comment]
Seems to be working! Although there is a small extra whitespace that gets added when the reload icon is hidden. It was very noticeable when I had all three extensions installed (to test), but it's very minor with only one of them, which is definitely the normal use case. I have no issues merging as-is, but if you're interested in fixing it, I'll wait a little longer.

**Comment by Madis0** [comment]
> Although there is a small extra whitespace that gets added when the reload icon is hidden. 

I have been trying to fix it, going from 1.1 (copied) to 1.4. Now I think the highest I can go is 1.5, because going further - such as 1.7 - is going to hide other PageActions in compact theme (though it looks good on normal). But yeah, I think it is too small of an issue to bother with density-specific sizes, merge it! 😛

**Comment by Timvde** [comment]
Sure thing! Thanks!

**Pull request merged**
