### PR TITLE
Navbar auto hide update for 58+ compatibility, and add Bookmark bar support

### PR DESCRIPTION
**Pull request by AlexVallat**
58+ removes the --tab-toolbar-navbar-overlap variable, so some re-jigging is required.

I've also fixed an issue where the spacers on the nav bar wouldn't count as hover-able areas, and added support for hiding the bookmark bar too (if that is visible). I'm not sure if that should be a separate file or not, I suppose it's possible you would want to auto-hide only one or the other, but to me it made more sense that they would both hide or show together.

### CODE REVIEW

**Comment by Aiolikos** [comment]
dude thanks for your work. I ve a theme though; the auto hide bookmark toolbar works but the bookmarks dont appear. it appears only space. what happen?? any advice would be highly appreciated

**Comment by AlexVallat** [comment]
Try turning the bookmarks toolbar off and on again, that might force it to repopulate.

**Comment by Aiolikos** [comment]
nothing man...I tried so many times but again the same.Only the first bookmark appears and after... free space. is it working properly for you? in any case I appreciate your help!
[https://imgur.com/a/wwIsP](url)

**Comment by AlexVallat** [comment]
It worked for me, yes. Can you tell me the version of Firefox and OS you are using? Also, I doubt it makes a difference, but can you check if disabling the theme fixes it?

**Comment by Aiolikos** [comment]
I use Firefox 57 on Windows 10 (64). I tried with the default theme with no success. Maybe I am doing something wrong man,  I don't really  know.

**Comment by AlexVallat** [comment]
Thanks, I'll give 57/Win10 a try in a VM when I get a chance, see if I can reproduce it.

**Comment by AlexVallat** [comment]
I've tried it a few times now, and I managed to reproduce the issue once. However, after restarting Firefox the bookmarks toolbar showed fully populated as normal. All I can suggest then is to restart Firefox and see if the problem just goes away.

**Comment by AlexVallat** [comment]
Ah, never mind, I figured it out - it works fine if Firefox starts with the default home page (so the address bar is focused on launch), but if Firefox starts with the navbar hidden then the issue occurs. I'll see if I can find a workaround.

**Comment by Aiolikos** [comment]
ohh  yes man I just saw it! it works fine with the default home page!!!this is the problem...thanks for your effort! if you can do something further,  then ok! thanks again

**Comment by AlexVallat** [comment]
OK, I've pushed a change which should allow it to work even if the nav bar is hidden at startup.

**Comment by Aiolikos** [comment]
you are awesome! Thank  you!

**Comment by dannycolin** [comment]
@AlexVallat There's a bug when the menubar is visible. https://imgur.com/a/UwXyk

**Comment by AlexVallat** [comment]
Sadly it is not possible to detect menu bar visibility at the `#navigator-toolbox` level using CSS, so I can not make it automatically account for whether it is visible or not.

If you want to have your menu bar always visible, you can add 20px onto the value of the `--nav-bar-height` variable at the top of the file, then it should be OK.

**Comment by Timvde** [comment]
> I'm not sure if that should be a separate file or not, I suppose it's possible you would want to auto-hide only one or the other, but to me it made more sense that they would both hide or show together.

I tend to agree. Could you move the file to the `toolbars` folder then, instead of `navbar`?

**Comment by AlexVallat** [comment]
No problem, I've moved it now.

**Comment by Timvde** [comment]
Sorry for being annoying, but you forgot to update the comment :) And while you're at it, I noticed that your file is missing a newline at the end. It's [POSIX standard](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline#729795) to include it.

**Comment by AlexVallat** [comment]
Merry Christmas. Not entirely sure what you meant about updating the comment, but I've assumed that you wanted it to mention that the bookmarks toolbar would be hidden too, so I've added that.

**Comment by Timvde** [comment]
Exactly what I meant, sorry for not being clear. Thanks!

**Pull request merged**
