### PR TITLE
Fix auto-hide urlbar for Firefox 75 megabar

### PR DESCRIPTION
**Pull request by Glandos**

### CODE REVIEW

**Comment by Glandos** [comment]
Fix #174

**Comment by Timvde** [comment]
Does this work in different density modes?

**Comment by Glandos** [comment]
The auto-hide.css does not behave correctly in different density.
So a variable should be introduced first, to get the toolbar height based on density.

For info, the variable `urlbar-toolbar-height` seems to be set dynamically on the `#urlbar` element's `style` attribute.

**Comment by Timvde** [comment]
Well, since it's currently broken, let's just merge it already, and I'll hopefully see a new PR coming in if somebody uses this on a different density.

**Pull request merged**
