### PR TITLE
add dark-autocomplete.css

### PR DESCRIPTION
**Pull request by hyperfekt**
CSS to adapt the autocomplete of the navbar from white to the colors of the dark theme.

### CODE REVIEW

**Comment by Timvde** [comment]
Thanks! Could you add newlines in between the different blocks? No further remarks, looking good :)

**Comment by hyperfekt** [comment]
It's called autocomplete in the HTML source, but it's well possible that's not the official name for it. I will probably make the changes tomorrow, feel free to edit it yourself if you'd like to merge earlier.

**Comment by Timvde** [comment]
Hmm, it seems that you're right. I'm on the fence. While you're technically correct, I want it to be clear for users, and I believe "location bar dropdown" would be nicer. If you feel strongly otherwise, I will also accept it, as long as you move it to the navbar directory. That should give enough context.

**Comment by hyperfekt** [comment]
No, I am definitely in agreement. I was surprised about the naming myself
when I discovered it. 'Autocomplete' is far from obvious.

**Comment by hyperfekt** [comment]
Here we go. :)

**Comment by Timvde** [comment]
Awesome, thank you very much!

**Pull request merged**
